# Academic CV & Publication Website
# Built with Jekyll and optimized for Obsidian integration

title: "Pavel Ievlev"
subtitle: "PhD in Probability Theory and Statistics"
email: pavel.ievlev@unil.ch
description: >-
  Personal academic website.

# Profile photo (add your photo to assets/images/ and update this path)
profile_photo: "/vault/assets/photo.jpeg"

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Social links
github_username: ievlevpn
orcid: 0000-0003-3329-5741
scholar: 3z8jrW8AAAAJ
linkedin:

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections configuration
collections_dir: vault
collections:
  publications:
    output: true
    permalink: /publications/:name/
    sort_by: date
  experience:
    output: true
    permalink: /experience/:name/
    sort_by: start_date
  education:
    output: false
    sort_by: graduation_year
  projects:
    output: true
    permalink: /projects/:name/
    sort_by: date
  talks:
    output: true
    permalink: /talks/:name/
    sort_by: date
  teaching:
    output: true
    permalink: /teaching/:name/
    sort_by: semester
  pages:
    output: true
    permalink: /:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"
  - scope:
      path: ""
      type: "experience"
    values:
      layout: "experience"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "talks"
    values:
      layout: "talk"
  - scope:
      path: ""
      type: "teaching"
    values:
      layout: "teaching"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Sass configuration
sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - .obsidian/
  - vault/templates

# Academic-specific settings
academic:
  show_publications_on_home: true
  publications_limit: 5
  show_recent_talks: true
  cv_pdf_path: "vault/assets/cv.pdf"
  research_interests:
    - "Extreme value theory"
    - "Large deviations"
    - "Gaussian random fields"
    - "Stochastic analysis"